services:
    app.promotion.repository:
        class: AppBundle\Repositroy\PromotionRepository
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'AppBundle\Entity\Promotion'
        calls:
            - [setContainer, ['@service_container']]

    app.promotion.promotion_factory:
        class: AppBundle\Promotion\PromotionFactory
        arguments:
            - '@app.promotion.repository'

    app.promotion.twenty_percent_discount:
        class: AppBundle\Promotion\TwentyPercentDiscountPromotion
        tags:
            - { name: 'promotion' }
