services:
    app.promotion.promotion_repository:
        class: AppBundle\Repository\PromotionRepository
        arguments:
            - 'AppBundle\Entity\Promotion'
        calls:
            - [setContainer, ['@service_container']]

    app.promotion.promotion_item_repository:
        class: AppBundle\Repository\PromotionItemRepository
        arguments:
            - 'AppBundle\Entity\PromotionItem'

    app.promotion.promotion_benefit_repository:
        class: AppBundle\Repository\PromotionBenefitRepository
        arguments:
            - 'AppBundle\Entity\TransactionBenefit'

    app.promotion.promotion_factory:
        class: AppBundle\Promotion\PromotionFactory
        arguments:
            - '@app.promotion.promotion_repository'

    app.promotion.promotion_benefit_subscriber:
        class: AppBundle\Promotion\PromotionBenefitSubscriber
        arguments:
            - '@app.promotion.promotion_item_repository'
        tags:
            - { name: 'doctrine.event_subscriber' }

    app.promotion.promotable_subscriber:
        class: AppBundle\Promotion\PromotableSubscriber
        arguments:
            - '@app.promotion.promotion_benefit_repository'
            - '@app.promotion.promotion_factory'
        tags:
            - { name: 'doctrine.event_subscriber' }

    app.promotion.twenty_percent_discount:
        class: AppBundle\Promotion\TwentyPercentDiscountPromotion
        arguments:
            - 'AppBundle\Entity\TransactionBenefit'
        tags:
            - { name: 'promotion' }

    app.promotion.data_provider.promotion_data_provider:
        class: AppBundle\Promotion\DataProvider\PromotionDataProvider
        arguments:
            - '%promotion%'
        calls:
            - [setContainer, ['@service_container']]
        tags:
            -  { name: 'api_platform.collection_data_provider', priority: 2 }
            -  { name: 'api_platform.item_data_provider', priority: 2 }
