# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.action_logger.action_logger_subscriber:
        class: AppBundle\ActionLogger\ActionLoggableSubscriber
        arguments:
            - '@security.token_storage'
        tags:
            - { name: 'doctrine.event_subscriber' }

    app.price.data_provider.price_calculator_data_provider:
        class: AppBundle\Price\DataProvider\PriceCalculatorDataProvider
        arguments:
            - '%price_calculator%'
        calls:
            - [setContainer, ['@service_container']]
        tags:
            -  { name: 'api_platform.collection_data_provider', priority: 2 }
            -  { name: 'api_platform.item_data_provider', priority: 2 }

    app.promotion.data_provider.promotion_data_provider:
        class: AppBundle\Promotion\DataProvider\PromotionDataProvider
        arguments:
            - '%promotion%'
        calls:
            - [setContainer, ['@service_container']]
        tags:
            -  { name: 'api_platform.collection_data_provider', priority: 2 }
            -  { name: 'api_platform.item_data_provider', priority: 2 }

    owner.search_filter:
        parent:    'api_platform.doctrine.orm.search_filter'
        arguments: [ { owner: 'exact' } ]
        tags:      [ { name: 'api_platform.filter', id: 'owner.search' } ]
