# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.action_logger.action_logger_subscriber:
        class: AppBundle\ActionLogger\ActionLoggableSubscriber
        arguments:
            - '@security.token_storage'
        tags:
            - { name: doctrine.event_subscriber }

    app.asset.asset_uploader:
        class: AppBundle\Asset\AssetUploader
        arguments:
            - '%kernel.root_dir%/../web/uploads'

    app.asset.action_logger_subscriber:
        class: AppBundle\Asset\AssetSubscriber
        arguments:
            - '@app.asset.asset_uploader'
        tags:
            - { name: doctrine.event_subscriber }
