services:
    app.shopping_cart.shopping_cart_repository:
        class: AppBundle\Repository\ShoppingCartRepository
        arguments:
            - 'AppBundle\Entity\ShoppingCart'

    app.shopping_cart.shopping_cart_owner_subscriber:
        class: AppBundle\ShoppingCart\ShoppingCartOwnerSubscriber
        arguments:
            - '@app.shopping_cart.shopping_cart_repository'
        tags:
            - { name: 'doctrine.event_subscriber' }

    app.shopping_cart.shopping_cart_item_repository:
        class: AppBundle\Repository\ShoppingCartItemRepository
        arguments:
            - 'AppBundle\Entity\ShoppingCartItem'

    app.shopping_cart.shopping_cart_subscriber:
        class: AppBundle\ShoppingCart\ShoppingCartSubscriber
        arguments:
            - '@app.shopping_cart.shopping_cart_item_repository'
        tags:
            - { name: 'doctrine.event_subscriber' }

    app.shopping_cart.shopping_cart_item_subscriber:
        class: AppBundle\ShoppingCart\ShoppingCartItemSubscriber
        arguments:
            - '@app.shopping_cart.shopping_cart_item_repository'
            - '@app.product.product_factory'
        tags:
            - { name: 'doctrine.event_subscriber' }